src/CosmosPagination.Web/Pages/DataManagement.cshtml.cs
using CosmosPagination.Cosmos;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CosmosPagination.Web.Pages;

public class DataModel(IRepository repository) : PageModel
{
    public string Message { get; private set; } = string.Empty;

    private readonly IRepository _repository = repository;

    public void OnGet() { }
    public async Task OnPostSeedAsync()
    {
        await _repository.Seed();
        Message = "Succesfully seeded database";
    }

    public async Task OnPostDeleteAsync()
    {
        await _repository.Delete();
        Message = "Succesfully deleted database and container";
    }
}

src/CosmosPagination.Web/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CosmosPagination.Web.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

src/CosmosPagination.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CosmosPagination.Web.Pages;

public class IndexModel : PageModel
{
    public void OnGet()
    {

    }
}

src/CosmosPagination.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CosmosPagination.Web.Pages;

public class PrivacyModel : PageModel
{
    public void OnGet()
    {
    }
}

src/CosmosPagination.Web/Pages/ViewData.cshtml.cs
using CosmosPagination.Cosmos;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;

namespace CosmosPagination.Web.Pages;

public class ViewDataModel(IRepository repository, IMemoryCache memoryCache) : PageModel
{
    public IEnumerable<Product> Products { get; private set; } = [];
    public long PageCount { get; private set; } = 1;
    public string? ContinuationToken { get; private set; }

    private readonly IRepository _repository = repository;
    private readonly IMemoryCache _memoryCache = memoryCache;

    private const int _pageSize = 25;
    private const string _pageCountKey = "PageCount";

    public async Task OnGetAsync()
    {
        var itemCount = await _repository.GetItemCount();
        var pageCount = itemCount / _pageSize;
        _memoryCache.Set(_pageCountKey, pageCount);
    }

    public async Task OnPostLoadUnpaginatedAsync() => Products = await _repository.GetAll();
    public async Task OnPostLoadSkipTake(int pageNumber)
    {
        PageCount = _memoryCache.Get<long>(_pageCountKey);
        Products = await _repository.GetPaginatedResults(pageNumber, _pageSize);
    }
    public async Task OnPostLoadTokens(string? providedToken = null)
    {
        var (products, continuationToken) = await _repository.GetTokenPaginatedResults(_pageSize, providedToken);
        Products = products;
        ContinuationToken = continuationToken;
    }
}

src/CosmosPagination.Web/Pages/Data.cshtml
@page
@model CosmosPagination.Web.Pages.DataModel

@{
    ViewData["Title"] = "Data viewer";
}

<div>
    <form asp-page-handler="seed" method="post">
        <button class="btn btn-primary">Seed data</button>
    </form>
    <button type="button" class="btn btn-danger">Delete data</button>
</div>

<div>
    <form asp-page-handler="getall" method="post">
        <button class=btn btn-primary>View all data unpaginated</button>
    </form>
</div>

src/CosmosPagination.Web/Pages/DataManagement.cshtml
@page
@model CosmosPagination.Web.Pages.DataModel

@{
    ViewData["Title"] = "Data management";
}

<div>
    <form class="d-inline" asp-page-handler="seed" method="post">
        <button class="btn btn-primary">Seed data</button>
    </form>
    <form class="d-inline" asp-page-handler="delete" method="post">
        <button class="btn btn-danger">Delete data</button>
    </form>
</div>
<br />
@if (!string.IsNullOrWhiteSpace(Model.Message))
{
    <div class="alert alert-success">
        @Model.Message
    </div>
}

src/CosmosPagination.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

src/CosmosPagination.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CosmosPagination.Web</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CosmosPagination.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CosmosPagination.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/DataManagement">Data management</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/ViewData">View Data</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CosmosPagination.Web - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/CosmosPagination.Web/Pages/ViewData.cshtml
@page
@model CosmosPagination.Web.Pages.ViewDataModel
@{
    ViewData["Title"] = "View data";
}

<div>
    <form class="d-inline" asp-page-handler="loadunpaginated" method="post">
        <button class="btn btn-primary">Load all data unpaginated</button>
    </form>
    <form class="d-inline" asp-page-handler="loadskiptake" method="post">
        <button class="btn btn-info">Load data using skip and take</button>
        <input type="hidden" name="pageNumber" value="1" />
    </form>
    <form class="d-inline" asp-page-handler="loadtokens" method="post">
        <button class="btn btn-info">Load data using continuation tokens</button>
        <input type="hidden" name="providedToken" value="@Model.ContinuationToken" />
    </form>
</div>
<br />
@if (Model.Products.Any())
{
    <div>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var product in Model.Products)
                {
                    <tr>
                        <td>@product.Id</td>
                        <td>@product.Name</td>
                        <td>@product.Price</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
@if (Model.PageCount > 1)
{
    <div>
        @{
            for (int i = 1; i < Model.PageCount; i++)
            {
                <form class="d-inline" asp-page-handler="loadskiptake" method="post">
                    <button class="link-primary">@i</button>
                    <input type="hidden" name="pageNumber" value="@i" />
                </form>
            }
        }
    </div>
}
@if (!string.IsNullOrWhiteSpace(Model.ContinuationToken))
{
    <div>
        <form class="d-inline" asp-page-handler="loadtokens" method="post">
            <button class="btn btn-primary">Next page</button>
            <input type="hidden" name="providedToken" value="@Model.ContinuationToken" />
        </form>
    </div>
}